/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PoliticaDeTrocasRouteImport } from './routes/politica-de-trocas'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as NovidadesRouteImport } from './routes/novidades'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AdminTemaRouteImport } from './routes/admin.tema'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminProdutosIdRouteImport } from './routes/admin.produtos.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeTrocasRoute = PoliticaDeTrocasRouteImport.update({
  id: '/politica-de-trocas',
  path: '/politica-de-trocas',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const NovidadesRoute = NovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemaRoute = AdminTemaRouteImport.update({
  id: '/admin/tema',
  path: '/admin/tema',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/admin/produtos',
  path: '/admin/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosIdRoute = AdminProdutosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProdutosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/favoritos': typeof FavoritosRoute
  '/novidades': typeof NovidadesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-trocas': typeof PoliticaDeTrocasRoute
  '/sobre': typeof SobreRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/tema': typeof AdminTemaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/favoritos': typeof FavoritosRoute
  '/novidades': typeof NovidadesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-trocas': typeof PoliticaDeTrocasRoute
  '/sobre': typeof SobreRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/tema': typeof AdminTemaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/contato': typeof ContatoRoute
  '/favoritos': typeof FavoritosRoute
  '/novidades': typeof NovidadesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-trocas': typeof PoliticaDeTrocasRoute
  '/sobre': typeof SobreRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/tema': typeof AdminTemaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/contato'
    | '/favoritos'
    | '/novidades'
    | '/politica-de-privacidade'
    | '/politica-de-trocas'
    | '/sobre'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/produtos'
    | '/admin/tema'
    | '/categoria/$slug'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/produtos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/contato'
    | '/favoritos'
    | '/novidades'
    | '/politica-de-privacidade'
    | '/politica-de-trocas'
    | '/sobre'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/produtos'
    | '/admin/tema'
    | '/categoria/$slug'
    | '/produto/$slug'
    | '/admin'
    | '/admin/produtos/$id'
  id:
    | '__root__'
    | '/'
    | '/busca'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/contato'
    | '/favoritos'
    | '/novidades'
    | '/politica-de-privacidade'
    | '/politica-de-trocas'
    | '/sobre'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/produtos'
    | '/admin/tema'
    | '/categoria/$slug'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/produtos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContaRoute: typeof ContaRoute
  ContatoRoute: typeof ContatoRoute
  FavoritosRoute: typeof FavoritosRoute
  NovidadesRoute: typeof NovidadesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PoliticaDeTrocasRoute: typeof PoliticaDeTrocasRoute
  SobreRoute: typeof SobreRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProdutosRoute: typeof AdminProdutosRouteWithChildren
  AdminTemaRoute: typeof AdminTemaRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-trocas': {
      id: '/politica-de-trocas'
      path: '/politica-de-trocas'
      fullPath: '/politica-de-trocas'
      preLoaderRoute: typeof PoliticaDeTrocasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novidades': {
      id: '/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof NovidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tema': {
      id: '/admin/tema'
      path: '/admin/tema'
      fullPath: '/admin/tema'
      preLoaderRoute: typeof AdminTemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos/$id': {
      id: '/admin/produtos/$id'
      path: '/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AdminProdutosIdRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
  }
}

interface AdminProdutosRouteChildren {
  AdminProdutosIdRoute: typeof AdminProdutosIdRoute
}

const AdminProdutosRouteChildren: AdminProdutosRouteChildren = {
  AdminProdutosIdRoute: AdminProdutosIdRoute,
}

const AdminProdutosRouteWithChildren = AdminProdutosRoute._addFileChildren(
  AdminProdutosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ContaRoute: ContaRoute,
  ContatoRoute: ContatoRoute,
  FavoritosRoute: FavoritosRoute,
  NovidadesRoute: NovidadesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PoliticaDeTrocasRoute: PoliticaDeTrocasRoute,
  SobreRoute: SobreRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProdutosRoute: AdminProdutosRouteWithChildren,
  AdminTemaRoute: AdminTemaRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
