// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xozlbyifpjolqhiglsiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvemxieWlmcGpvbHFoaWdsc2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg4OTAxMzAsImV4cCI6MjEwNDQ2NjEzMH0.q0FBaRfvKwz1tT457Xe9mTC4qtm5YbQ_btr8c6nK5WE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});