// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vipneefuiharvfnqcali.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpcG5lZWZ1aWhhcnZmbnFjYWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ5MzcyNDYsImV4cCI6MjEwMDUxMzI0Nn0.hPGHYdumo1R8rPP2Ggwm6X9JjLgNmn0wz1P63b61B70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});